FROM ubuntu

RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get install -y python-pip python-numpy python-scipy \
                       python-matplotlib python-sklearn python-beautifulsoup \
                       python-parse

RUN mkdir -p /tmp
