CELERY_RESULT_BACKEND = "amqp"

CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_SERIALIZER = 'json'  # NOTE: MUST BE SET TO JSON

CELERY_ACCEPT_CONTENT = ['json']

CELERYD_LOG_LEVEL = "DEBUG"

INSTALLED_APPS = ["mltsp"]

CELERY_IMPORTS = ("mltsp", "celery_tasks")
